package pdt.cliente.swing.equipo;

import cfc.servidor.DTOs.BajaEquipoDTO;
import cfc.servidor.DTOs.EquipoDTO;
import cfc.servidor.enumerados.EstadosEnum;
import pdt.cliente.App;
import pdt.cliente.Conexion;

import javax.swing.*;
import java.time.LocalDate;

/**
 * Clase que representa la ventana de baja de equipo.
 */
public class JFBajaEquipo extends javax.swing.JFrame {


    // ======================== Atributos ========================
    /**
     * Equipo pasado por parámetro. (Para dar de baja)
     */
    private final EquipoDTO EQUIPO_PASADO;

    // ============================= Constructor =============================

    /**
     * Constructor de la clase.<br>
     * Inicializa los componentes de la ventana.
     */
    public JFBajaEquipo(EquipoDTO equipo) {
        EQUIPO_PASADO = equipo;
        initComponents();
        cargarDatos();
    }

    // =============================== Métodos ===============================

    /**
     * Método que se ejecuta al presionar el botón "Baja".<br>
     * Da de baja el equipo seleccionado.
     */
    private void cargarDatos() {
        txtNombreEquipo.setText(EQUIPO_PASADO.getNombre());
        txtNombreUsuario.setText(App.getUsuarioLogueado().getNombre());
        dcFechaBaja.setDate(java.sql.Date.valueOf(LocalDate.now()));
    }

    // =============================== Eventos ===============================

    /**
     * Método que se ejecuta al presionar el botón "Cancelar".<br>
     * Cierra la ventana y muestra el listado de equipos.
     *
     * @param evt Evento de acción.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        JFListadoEquipos.getInstancia().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que se ejecuta al presionar el botón "Baja".<br>
     * Da de baja el equipo seleccionado.
     *
     * @param evt Evento de acción.
     */
    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        try {
            JOptionPane opcion = new JOptionPane();
            opcion.setMessage("¿Seguro que quieres dar de baja este Equipo?");
            opcion.setOptions(new Object[]{"Confirmar", "Cancelar"});
            int respuesta = opcion.showConfirmDialog(this, "Confirmación", "Confirmar baja", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                BajaEquipoDTO bajaEquipoDTO = new BajaEquipoDTO();
                EquipoDTO equipoDTO = Conexion.rec_equipo.obtenerPorID(EQUIPO_PASADO.getId());
                bajaEquipoDTO.setIdEquipo(equipoDTO.getId());
                LocalDate fechaBaja = LocalDate.now();
                bajaEquipoDTO.setFechaBaja(fechaBaja);
                bajaEquipoDTO.setObservaciones(txtComentarios.getText());
                bajaEquipoDTO.setMotivo(txtMotivo.getText());
                bajaEquipoDTO.setIdUsuario(App.getUsuarioLogueado().getId());
                equipoDTO.setEstado(EstadosEnum.ELIMINADO);
                Conexion.rec_equipo.actualizar(equipoDTO);
                Conexion.rec_bajaEquipo.registrar(bajaEquipoDTO);
                JOptionPane.showMessageDialog(this, "Baja realizada con éxito");
                dispose();
                JFListadoEquipos jfListadoEquipos = JFListadoEquipos.getInstancia();
                jfListadoEquipos.recargarFilas();
                jfListadoEquipos.aplicarFiltros();
                jfListadoEquipos.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Baja cancelada");
            }

        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    // =============================== UI ===============================

    /*
     * Método controlado por el editor de formularios, encargado
     * de inicializar y estructurar los elementos del formulario.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel background = new javax.swing.JPanel();
        txtNombreEquipo = new javax.swing.JTextField();
        javax.swing.JLabel lblNombre = new javax.swing.JLabel();
        javax.swing.JLabel lblFichaUsuario = new javax.swing.JLabel();
        javax.swing.JLabel lblNombreEquipo = new javax.swing.JLabel();
        javax.swing.JLabel lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        javax.swing.JLabel lblFechaBaja = new javax.swing.JLabel();
        javax.swing.JLabel lblComentarios = new javax.swing.JLabel();
        dcFechaBaja = new com.toedter.calendar.JDateChooser();
        txtComentarios = new java.awt.TextArea();
        javax.swing.JButton btnCancelar = new javax.swing.JButton();
        javax.swing.JButton btnBaja = new javax.swing.JButton();
        javax.swing.JLabel lblMotivo = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreEquipo.setEditable(false);
        txtNombreEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblFichaUsuario.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lblFichaUsuario.setText("Registrar Equipo");

        lblNombreEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreEquipo.setText("Nombre de equipo");

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreUsuario.setText("Nombre del usuario");

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblFechaBaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaBaja.setText("Fecha de la baja");

        lblComentarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblComentarios.setText("Comentarios");

        dcFechaBaja.setEnabled(false);

        btnCancelar.setBackground(new java.awt.Color(132, 132, 132));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBaja.setBackground(new java.awt.Color(38, 34, 249));
        btnBaja.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMotivo.setText("Motivo de la baja");

        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(lblComentarios)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtComentarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFechaBaja)
                                            .addComponent(lblMotivo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMotivo)
                                            .addComponent(dcFechaBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombreUsuario)
                                            .addComponent(lblNombreEquipo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lblFichaUsuario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFichaUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaBaja)
                    .addComponent(dcFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMotivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables de los componentes manejados por el editor de formularios.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcFechaBaja;
    private java.awt.TextArea txtComentarios;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
