package pdt.cliente.swing.ubicacion;

import cfc.servidor.DTOs.UbicacionDTO;
import cfc.servidor.enumerados.SectoresEnum;
import cfc.servidor.exepciones.EntityException;
import pdt.cliente.Conexion;

import javax.swing.*;

/**
 * Clase que representa la ventana de la ficha de ubicación.
 */
public class JFFichaDeUbicacion extends javax.swing.JFrame {

    // ======================== Atributos ========================
    /**
     * Ubicación seleccionada para mostrar en la ficha.
     */
    private final UbicacionDTO UBICACION_SELECCIONADA;

    // ============================= Constructor =============================

    /**
     * Constructor de la clase.<br>
     * Inicializa los componentes de la ventana.
     */
    public JFFichaDeUbicacion(UbicacionDTO ubicacion) {
        this.UBICACION_SELECCIONADA = ubicacion;
        initComponents();
        cargarComboBox();
        rellenarCampos();
    }

    // =============================== Métodos ===============================

    /**
     * Rellena los campos de la ficha con los datos de la ubicación seleccionada.
     */
    public void rellenarCampos() {
        this.txtNombre.setText(this.UBICACION_SELECCIONADA.getNombre());
        this.txtCama.setText(this.UBICACION_SELECCIONADA.getCama());
        this.cbxSector.setSelectedItem(this.UBICACION_SELECCIONADA.getSector());
        this.txtPiso.setText(this.UBICACION_SELECCIONADA.getPiso());
        this.txtNumero.setText(String.valueOf(this.UBICACION_SELECCIONADA.getNumero()));
        this.txtInstitucion.setText(this.UBICACION_SELECCIONADA.getInstitucion().toString());
    }

    /**
     * Carga los sectores en el ComboBox.
     */
    public void cargarComboBox() {
        // Limpia el ComboBox
        this.cbxSector.removeAllItems();

        // Carga los sectores
        for (SectoresEnum sector : SectoresEnum.values()) {
            this.cbxSector.addItem(sector.name());
        }
    }

    // =============================== Eventos ===============================

    /**
     * Método que se ejecuta al presionar el botón de Actualizar.<br>
     * Actualiza la ubicación seleccionada con los datos ingresados.
     *
     * @param evt Evento de acción.
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed\
        try {
            UbicacionDTO ubicaciondto = new UbicacionDTO();
            ubicaciondto.setId(UBICACION_SELECCIONADA.getId());
            ubicaciondto.setInstitucion(UBICACION_SELECCIONADA.getInstitucion());
            ubicaciondto.setEstado(UBICACION_SELECCIONADA.getEstado());
            ubicaciondto.setCama(txtCama.getText());
            ubicaciondto.setNumero(Integer.parseInt(txtNumero.getText()));
            ubicaciondto.setNombre(txtNombre.getText());
            ubicaciondto.setSector(SectoresEnum.valueOf((String) cbxSector.getSelectedItem()));
            ubicaciondto.setPiso(txtPiso.getText());
            Conexion.rec_ubicacion.actualizar(ubicaciondto);
        }catch (EntityException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la ubicación.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * Método que se ejecuta al presionar el botón de Cancelar.<br>
     * Cierra la ventana actual y muestra la ventana de Dashboard.
     *
     * @param evt Evento de acción.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        JFListadoUbicacion.getInstancia().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // ================================= UI ==================================

    /*
     * Método controlado por el editor de formularios, encargado
     * de inicializar y estructurar los elementos del formulario.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel background = new javax.swing.JPanel();
        javax.swing.JLabel lblFichaEquipo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        javax.swing.JLabel lblNombre = new javax.swing.JLabel();
        javax.swing.JLabel lblSector = new javax.swing.JLabel();
        javax.swing.JLabel lblNumero = new javax.swing.JLabel();
        javax.swing.JLabel lblPiso = new javax.swing.JLabel();
        javax.swing.JLabel lblCama = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        javax.swing.JButton btnActualizar = new javax.swing.JButton();
        javax.swing.JButton btnCancelar = new javax.swing.JButton();
        txtCama = new javax.swing.JTextField();
        txtInstitucion = new javax.swing.JTextField();
        javax.swing.JLabel lblInstitucion = new javax.swing.JLabel();
        cbxSector = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFichaEquipo.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lblFichaEquipo.setText("Ficha Ubicación");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("Nombre");

        lblSector.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSector.setText("Sector");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumero.setText("Número");

        lblPiso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPiso.setText("Piso");

        lblCama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCama.setText("Cama");

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPiso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnActualizar.setBackground(new java.awt.Color(38, 34, 249));
        btnActualizar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(132, 132, 132));
        btnCancelar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtInstitucion.setEditable(false);
        txtInstitucion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblInstitucion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInstitucion.setText("Institucion");

        cbxSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(lblFichaEquipo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(backgroundLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCama)
                                                        .addComponent(lblPiso)
                                                        .addComponent(lblNumero)
                                                        .addComponent(lblSector)
                                                        .addComponent(lblNombre)
                                                        .addComponent(lblInstitucion))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtInstitucion)
                                                        .addComponent(txtPiso, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtCama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                                        .addComponent(cbxSector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(17, 17, 17))
        );
        backgroundLayout.setVerticalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblFichaEquipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxSector))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumero)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPiso)
                                        .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCama)
                                        .addComponent(txtCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblInstitucion)
                                        .addComponent(txtInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables de los componentes manejados por el editor de formularios.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxSector;
    private javax.swing.JTextField txtCama;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
