package pdt.cliente.swing.usuario;

import pdt.cliente.App;
import pdt.cliente.swing.JFDashboard;
import pdt.cliente.swing.login.JFLogin;

import javax.swing.*;

/**
 * Clase que representa la ventana de Usuario.
 */
public class JFUsuario extends javax.swing.JFrame {

    // ======================== Atributos ========================
    /**
     * Instancia única de la clase (patrón Singleton).
     */
    private static JFUsuario instancia = null;

    // ============================= Constructor =============================

    /**
     * Constructor de la clase.<br>
     * Inicializa los componentes de la ventana.
     */
    private JFUsuario() {
        initComponents();

    }

    // =============================== Métodos ===============================

    /**
     * Método que devuelve la instancia única de la clase (patrón Singleton).
     *
     * @return Instancia única de la clase.
     */
    public static JFUsuario getInstancia() {
        if (instancia == null) {
            instancia = new JFUsuario();
        }
        instancia.lblUsuario.setText(App.getUsuarioLogueado().getUsername());
        return instancia;
    }

    // =============================== Eventos ===============================

    /**
     * Método que se ejecuta al presionar el botón de cancelar.
     *
     * @param evt Evento de acción.
     */
    private void btnCalcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcelarActionPerformed
        this.setVisible(false); // Oculta la ventana actual
        JFDashboard.getInstancia().setVisible(true); // Muestra la ventana de Dashboard
    }//GEN-LAST:event_btnCalcelarActionPerformed

    /**
     * Método que se ejecuta al presionar el botón de Mi Usuario.
     *
     * @param evt Evento de acción.
     */
    private void btnMiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiUsuarioActionPerformed
        this.setVisible(false); // Oculta la ventana actual
        JFUsuarioPropio usuarioPropio = new JFUsuarioPropio();
        usuarioPropio.setVisible(true);
    }//GEN-LAST:event_btnMiUsuarioActionPerformed

    /**
     * Método que se ejecuta al presionar el botón de Salir.
     *
     * @param evt Evento de acción.
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Muestra un mensaje de confirmación
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        // Si el usuario cancela, no hace nada
        if (opcion != JOptionPane.YES_OPTION) return;

        this.setVisible(false); // Oculta la ventana actual
        JOptionPane.showMessageDialog(this, "Sesión cerrada."); // Muestra un mensaje de confirmación

        // Limpia los campos del formulario de login y lo muestra
        JFLogin jFLogin = JFLogin.getInstancia();
        jFLogin.limpiarCampos();
        jFLogin.setVisible(true);

    }//GEN-LAST:event_btnSalirActionPerformed

    // ================================= UI ==================================

    /*
     * Método controlado por el editor de formularios, encargado
     * de inicializar y estructurar los elementos del formulario.
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel background = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        javax.swing.JButton btnCalcelar = new javax.swing.JButton();
        javax.swing.JButton btnMiUsuario = new javax.swing.JButton();
        javax.swing.JButton btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lblUsuario.setText("Usuario.Usuario");

        btnCalcelar.setBackground(new java.awt.Color(132, 132, 132));
        btnCalcelar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnCalcelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcelar.setText("Cancelar");
        btnCalcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcelarActionPerformed(evt);
            }
        });

        btnMiUsuario.setBackground(new java.awt.Color(38, 34, 249));
        btnMiUsuario.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnMiUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnMiUsuario.setText("Mi Usuario");
        btnMiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(38, 34, 249));
        btnSalir.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Cerrar Sesión");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcelar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnMiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables de los componentes manejados por el editor de formularios.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
